// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(QuanLyHieuSachNhaNamContext))]
    partial class QuanLyHieuSachNhaNamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.TblChiTietHoaDon", b =>
                {
                    b.Property<string>("SMaHd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaHD");

                    b.Property<string>("SMaSach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaSach");

                    b.Property<double>("FDongia")
                        .HasColumnType("float")
                        .HasColumnName("fDongia");

                    b.Property<double>("FThanhtien")
                        .HasColumnType("float")
                        .HasColumnName("fThanhtien");

                    b.Property<int>("ISoluong")
                        .HasColumnType("int")
                        .HasColumnName("iSoluong");

                    b.HasKey("SMaHd", "SMaSach");

                    b.HasIndex("SMaSach");

                    b.ToTable("tblChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblChiTietNhap", b =>
                {
                    b.Property<string>("MaPn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaPN");

                    b.Property<string>("SMasach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMasach");

                    b.Property<double>("FDongia")
                        .HasColumnType("float")
                        .HasColumnName("fDongia");

                    b.Property<double>("FThanhtien")
                        .HasColumnType("float")
                        .HasColumnName("fThanhtien");

                    b.Property<int>("ISoluong")
                        .HasColumnType("int")
                        .HasColumnName("iSoluong");

                    b.HasKey("MaPn", "SMasach");

                    b.HasIndex("SMasach");

                    b.ToTable("tblChiTietNhap", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblHoaDon", b =>
                {
                    b.Property<string>("SMaHd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaHD");

                    b.Property<DateOnly>("DNgaylap")
                        .HasColumnType("date")
                        .HasColumnName("dNgaylap");

                    b.Property<double>("FTongHd")
                        .HasColumnType("float")
                        .HasColumnName("fTongHD");

                    b.Property<string>("SMaNv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaNV");

                    b.HasKey("SMaHd")
                        .HasName("PK__tblHoaDo__328E4D551579AD7F");

                    b.HasIndex("SMaNv");

                    b.ToTable("tblHoaDon", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblNhanvien", b =>
                {
                    b.Property<string>("SMaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaNV");

                    b.Property<bool>("BGioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("bGioitinh");

                    b.Property<bool>("BTrangthai")
                        .HasColumnType("bit")
                        .HasColumnName("bTrangthai");

                    b.Property<bool>("BVaitro")
                        .HasColumnType("bit")
                        .HasColumnName("bVaitro");

                    b.Property<DateOnly?>("DNgaysinh")
                        .HasColumnType("date")
                        .HasColumnName("dNgaysinh");

                    b.Property<DateOnly>("DNgayvaolam")
                        .HasColumnType("date")
                        .HasColumnName("dNgayvaolam");

                    b.Property<double>("FLuong")
                        .HasColumnType("float")
                        .HasColumnName("fLuong");

                    b.Property<string>("SCccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sCCCD");

                    b.Property<string>("SDiachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sDiachi");

                    b.Property<string>("SSdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("sSDT");

                    b.Property<string>("STenNv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTenNV");

                    b.HasKey("SMaNv")
                        .HasName("PK__tblNhanv__328E1C0FB7CCACC6");

                    b.HasIndex(new[] { "SCccd" }, "UQ__tblNhanv__31AF424FA59EB373")
                        .IsUnique()
                        .HasFilter("[sCCCD] IS NOT NULL");

                    b.ToTable("tblNhanvien", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblNhap", b =>
                {
                    b.Property<string>("MaPn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaPN");

                    b.Property<bool>("BLoai")
                        .HasColumnType("bit")
                        .HasColumnName("bLoai");

                    b.Property<DateOnly>("DNgaylap")
                        .HasColumnType("date")
                        .HasColumnName("dNgaylap");

                    b.Property<double>("FTongGt")
                        .HasColumnType("float")
                        .HasColumnName("fTongGT");

                    b.Property<string>("SMaNv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaNV");

                    b.HasKey("MaPn")
                        .HasName("PK__tblNhap__2725E7F0A292050E");

                    b.HasIndex("SMaNv");

                    b.ToTable("tblNhap", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblSach", b =>
                {
                    b.Property<string>("SMasach")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMasach");

                    b.Property<double>("IDongia")
                        .HasColumnType("float")
                        .HasColumnName("iDongia");

                    b.Property<int>("ISoluong")
                        .HasColumnType("int")
                        .HasColumnName("iSoluong");

                    b.Property<string>("SNxb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sNXB");

                    b.Property<string>("STenTg")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTenTG");

                    b.Property<string>("STensach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sTensach");

                    b.Property<string>("STheloai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sTheloai");

                    b.HasKey("SMasach")
                        .HasName("PK__tblSach__EA6DC7103193D482");

                    b.ToTable("tblSach", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblTaikhoan", b =>
                {
                    b.Property<string>("SMaNv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sMaNV");

                    b.Property<string>("SMatkhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sMatkhau");

                    b.HasKey("SMaNv")
                        .HasName("PK__tblTaikh__328E1C0FCE34D502");

                    b.ToTable("tblTaikhoan", (string)null);
                });

            modelBuilder.Entity("Domain.Models.TblChiTietHoaDon", b =>
                {
                    b.HasOne("Domain.Models.TblHoaDon", "SMaHdNavigation")
                        .WithMany("TblChiTietHoaDons")
                        .HasForeignKey("SMaHd")
                        .IsRequired()
                        .HasConstraintName("FK_tblChiTietHoaDon_tblHoaDon");

                    b.HasOne("Domain.Models.TblSach", "SMaSachNavigation")
                        .WithMany("TblChiTietHoaDons")
                        .HasForeignKey("SMaSach")
                        .IsRequired()
                        .HasConstraintName("FK_tblChiTietHoaDon_tblSach");

                    b.Navigation("SMaHdNavigation");

                    b.Navigation("SMaSachNavigation");
                });

            modelBuilder.Entity("Domain.Models.TblChiTietNhap", b =>
                {
                    b.HasOne("Domain.Models.TblNhap", "MaPnNavigation")
                        .WithMany("TblChiTietNhaps")
                        .HasForeignKey("MaPn")
                        .IsRequired()
                        .HasConstraintName("FK_tblChiTietNhap_tblNhap");

                    b.HasOne("Domain.Models.TblSach", "SMasachNavigation")
                        .WithMany("TblChiTietNhaps")
                        .HasForeignKey("SMasach")
                        .IsRequired()
                        .HasConstraintName("FK_tblChiTietNhap_tblSach");

                    b.Navigation("MaPnNavigation");

                    b.Navigation("SMasachNavigation");
                });

            modelBuilder.Entity("Domain.Models.TblHoaDon", b =>
                {
                    b.HasOne("Domain.Models.TblNhanvien", "SMaNvNavigation")
                        .WithMany("TblHoaDons")
                        .HasForeignKey("SMaNv")
                        .IsRequired()
                        .HasConstraintName("FK_tblHoaDon_tblNhanvien");

                    b.Navigation("SMaNvNavigation");
                });

            modelBuilder.Entity("Domain.Models.TblNhap", b =>
                {
                    b.HasOne("Domain.Models.TblNhanvien", "SMaNvNavigation")
                        .WithMany("TblNhaps")
                        .HasForeignKey("SMaNv")
                        .IsRequired()
                        .HasConstraintName("FK_tblNhap_tblNhanvien");

                    b.Navigation("SMaNvNavigation");
                });

            modelBuilder.Entity("Domain.Models.TblTaikhoan", b =>
                {
                    b.HasOne("Domain.Models.TblNhanvien", "SMaNvNavigation")
                        .WithOne("TblTaikhoan")
                        .HasForeignKey("Domain.Models.TblTaikhoan", "SMaNv")
                        .IsRequired()
                        .HasConstraintName("FK_tblTaikhoan_tblNhanvien");

                    b.Navigation("SMaNvNavigation");
                });

            modelBuilder.Entity("Domain.Models.TblHoaDon", b =>
                {
                    b.Navigation("TblChiTietHoaDons");
                });

            modelBuilder.Entity("Domain.Models.TblNhanvien", b =>
                {
                    b.Navigation("TblHoaDons");

                    b.Navigation("TblNhaps");

                    b.Navigation("TblTaikhoan");
                });

            modelBuilder.Entity("Domain.Models.TblNhap", b =>
                {
                    b.Navigation("TblChiTietNhaps");
                });

            modelBuilder.Entity("Domain.Models.TblSach", b =>
                {
                    b.Navigation("TblChiTietHoaDons");

                    b.Navigation("TblChiTietNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
